"""
Seed Data for GramNiti AI
Contains verified official government schemes, location datasets with DEMO DATA labels,
business templates with transparent simulation assumptions, and official source registry entries.
"""

from typing import List, Dict
from .models import Location, Business, Scheme

DEMO_LOCATIONS: List[Dict] = [
    {
        "location_id": "LOC_BARAMATI_01",
        "village_name": "Malegaon Budruk",
        "gram_panchayat": "Malegaon Gram Panchayat",
        "block_taluka": "Baramati",
        "district": "Pune",
        "state": "Maharashtra",
        "pincode": "413115",
        "population": 4850,
        "primary_livelihood": "Sugarcane Agriculture, Dairy Farming & Agro-processing",
        "agricultural_produce": ["Sugarcane", "Wheat", "Fodder Maize", "Vegetables"],
        "livestock_population": {"Crossbred Cows": 1420, "Buffaloes": 910, "Goats": 450},
        "market_access_distance_km": 5.2,
        "bank_branch_distance_km": 2.1,
        "cold_storage_available": True,
        "power_reliability_hours_per_day": 20.5,
        "water_availability": "Nira Left Bank Canal & Borewell",
        "is_demo_data": True
    },
    {
        "location_id": "LOC_KHED_02",
        "village_name": "Shindewadi",
        "gram_panchayat": "Shindewadi Gram Panchayat",
        "block_taluka": "Khed (Rajgurunagar)",
        "district": "Pune",
        "state": "Maharashtra",
        "pincode": "410505",
        "population": 2900,
        "primary_livelihood": "Dairy Farming, Poultry & Onion Cultivation",
        "agricultural_produce": ["Onion", "Potato", "Bajra", "Green Fodder"],
        "livestock_population": {"Crossbred Cows": 890, "Buffaloes": 430, "Poultry Birds": 12000},
        "market_access_distance_km": 8.0,
        "bank_branch_distance_km": 4.5,
        "cold_storage_available": False,
        "power_reliability_hours_per_day": 17.0,
        "water_availability": "Borewell & Farm Ponds",
        "is_demo_data": True
    },
    {
        "location_id": "LOC_AHMEDNAGAR_03",
        "village_name": "Loni Budruk",
        "gram_panchayat": "Loni Gram Panchayat",
        "block_taluka": "Rahata",
        "district": "Ahmednagar",
        "state": "Maharashtra",
        "pincode": "413736",
        "population": 6200,
        "primary_livelihood": "Dairy Co-operative, Guava/Pomegranate Orchards & Bio-fertilizer",
        "agricultural_produce": ["Pomegranate", "Guava", "Soybean", "Lucerne Fodder"],
        "livestock_population": {"Crossbred Cows": 2100, "Buffaloes": 680, "Sheep": 320},
        "market_access_distance_km": 3.0,
        "bank_branch_distance_km": 1.5,
        "cold_storage_available": True,
        "power_reliability_hours_per_day": 21.0,
        "water_availability": "Pravara River Canal & Drip Irrigation",
        "is_demo_data": True
    },
    {
        "location_id": "LOC_VARANASI_04",
        "village_name": "Kachnar",
        "gram_panchayat": "Kachnar Gram Panchayat",
        "block_taluka": "Rajatalab",
        "district": "Varanasi",
        "state": "Uttar Pradesh",
        "pincode": "221311",
        "population": 3800,
        "primary_livelihood": "Vegetable Farming, Food Processing & Handloom",
        "agricultural_produce": ["Tomato", "Green Pea", "Paddy", "Wheat"],
        "livestock_population": {"Cattle": 650, "Buffaloes": 820, "Goats": 410},
        "market_access_distance_km": 7.5,
        "bank_branch_distance_km": 3.0,
        "cold_storage_available": True,
        "power_reliability_hours_per_day": 18.5,
        "water_availability": "Tube Wells & Minor Canal",
        "is_demo_data": True
    },
    {
        "location_id": "LOC_INDORE_05",
        "village_name": "Dakachya",
        "gram_panchayat": "Dakachya Gram Panchayat",
        "block_taluka": "Sanwer",
        "district": "Indore",
        "state": "Madhya Pradesh",
        "pincode": "453771",
        "population": 4100,
        "primary_livelihood": "Soybean Processing, Wheat, Dairy & Custom Hiring Center",
        "agricultural_produce": ["Soybean", "Durum Wheat", "Gram", "Garlic"],
        "livestock_population": {"Cattle": 780, "Buffaloes": 940, "Goats": 280},
        "market_access_distance_km": 6.0,
        "bank_branch_distance_km": 2.5,
        "cold_storage_available": True,
        "power_reliability_hours_per_day": 19.0,
        "water_availability": "Narmada Malwa Link & Tube Wells",
        "is_demo_data": True
    }
]

VERIFIED_SCHEMES: List[Dict] = [
    {
        "scheme_id": "SCHEME_PMEGP",
        "code": "PMEGP",
        "name": "Prime Minister's Employment Generation Programme (PMEGP)",
        "official_name": "Prime Minister's Employment Generation Programme (PMEGP)",
        "scheme_tier": "CENTRAL",
        "state_name": "Central (Pan-India)",
        "funding_pattern": "100% Central Ministry of MSME",
        "category": "Central Sector Scheme",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MoMSME)",
        "implementing_agency": "Khadi and Village Industries Commission (KVIC)",
        "source_id": "SRC_KVIC",
        "target_beneficiaries": ["Rural Youth", "Women", "SC/ST/OBC Entrepreneurs", "SHGs", "Micro-Entrepreneurs"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Minority", "Women", "Ex-Serviceman"],
        "occupation_criteria": ["Farmer", "Unemployed Youth", "Artisan", "Rural Entrepreneur", "Self-Help Group Member"],
        "business_types": ["Manufacturing", "Service", "Agro-Processing", "Dairy Equipment Unit", "Food Processing", "Rural Workshop"],
        "education_criteria": "8th Pass for projects > ₹10 Lakh (Mfg) / > ₹5 Lakh (Service)",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 5000000.0,  # Up to ₹50 Lakh for Manufacturing, ₹20 Lakh for Service
        "subsidy_percentage_general_rural": 25.0,
        "subsidy_percentage_special_rural": 35.0,  # SC/ST/OBC/Women/Minority in rural areas get 35% margin money subsidy
        "subsidy_description": "25% for General category in rural areas; 35% for Special Categories (SC/ST/OBC/Women/Ex-Servicemen/Minorities) in rural areas. Subject to project cost limits.",
        "interest_subvention": "Normal Bank Interest Rate (Base Rate + Spread)",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 5.0,
        "stacking_eligible": True,
        "stacking_notes": "Can be stacked with state-level interest subvention schemes (e.g. Annasaheb Patil / UP MMGRY).",
        "repayment_period_months": 84,
        "moratorium_months": 6,
        "required_documents": ["AADHAAR", "PAN", "PROJECT_REPORT", "RURAL_AREA_CERTIFICATE", "CASTE_CERTIFICATE_IF_APPLICABLE", "EDUCATIONAL_PROOF", "BANK_STATEMENT"],
        "official_portal_url": "https://www.kviconline.gov.in/pmegpep/pmegphome/index.jsp",
        "guidelines_pdf_url": "https://msme.gov.in/sites/default/files/PMEGP_Guidelines.pdf",
        "effective_from": "2008-08-15",
        "effective_to": "2026-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2008-08-15",
        "source_updated_at": "2024-05-10",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_PMFME",
        "code": "PMFME",
        "name": "Pradhan Mantri Formalisation of Micro food processing Enterprises (PMFME)",
        "official_name": "Centrally Sponsored PM Formalisation of Micro Food Processing Enterprises Scheme",
        "scheme_tier": "CENTRALLY_SPONSORED",
        "state_name": "Central + State Shared",
        "funding_pattern": "60% Central Government : 40% State Government",
        "category": "Centrally Sponsored Scheme",
        "ministry": "Ministry of Food Processing Industries (MoFPI)",
        "implementing_agency": "State Nodal Agencies / MoFPI",
        "source_id": "SRC_MOFPI",
        "target_beneficiaries": ["Individual Micro Food Processors", "SHGs", "FPOs", "Producer Co-operatives"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women"],
        "occupation_criteria": ["Food Processor", "Farmer", "SHG Member", "Rural Entrepreneur"],
        "business_types": ["Food Processing", "Flour Mill", "Oil Extraction", "Spice Processing", "Dairy Products Processing", "Pickle & Jam Making", "Bakery"],
        "education_criteria": "8th Standard preferred",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 3000000.0,
        "subsidy_percentage_general_rural": 35.0,
        "subsidy_percentage_special_rural": 35.0,
        "subsidy_description": "Credit-linked capital subsidy @ 35% of the eligible project cost with a maximum ceiling of ₹10 Lakh per unit.",
        "interest_subvention": "Normal Bank Lending Rates",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 10.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows convergence with AIF (Agriculture Infrastructure Fund) for 3% interest subvention.",
        "repayment_period_months": 60,
        "moratorium_months": 6,
        "required_documents": ["AADHAAR", "PAN", "FOOD_SAFETY_DECLARATION", "PROJECT_REPORT", "BANK_STATEMENT", "UDYAM_REGISTRATION"],
        "official_portal_url": "https://pmfme.mofpi.gov.in/",
        "guidelines_pdf_url": "https://pmfme.mofpi.gov.in/pmfme/guidelines",
        "effective_from": "2020-06-29",
        "effective_to": "2026-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2020-06-29",
        "source_updated_at": "2024-04-12",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_PMMY_KISHORE",
        "code": "PMMY_KISHORE",
        "name": "Pradhan Mantri Mudra Yojana (PMMY) - Kishore Category",
        "official_name": "Pradhan Mantri MUDRA Yojana (PMMY) - Loans covering ₹50,000 to ₹5,00,000",
        "scheme_tier": "CENTRAL",
        "state_name": "Central (Pan-India)",
        "funding_pattern": "100% Credit Guarantee via CGFMU (DFS)",
        "category": "Central Financial Scheme",
        "ministry": "Ministry of Finance",
        "implementing_agency": "MUDRA / Scheduled Commercial Banks, RRBs, Small Finance Banks",
        "source_id": "SRC_MUDRA",
        "target_beneficiaries": ["Small Business Owners", "Artisans", "Dairy Farmers", "Kirana Shop Owners", "Youth"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women"],
        "occupation_criteria": ["Farmer", "Shopkeeper", "Micro-Entrepreneur", "Self-Employed"],
        "business_types": ["Dairy Farming", "Poultry Farming", "Retail Kirana", "Service Enterprise", "Small Manufacturing"],
        "education_criteria": "None mandatory",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 500000.0,
        "subsidy_percentage_general_rural": 0.0,
        "subsidy_percentage_special_rural": 0.0,
        "subsidy_description": "Zero direct capital subsidy. Advantage is collateral-free micro-credit backed by Credit Guarantee Fund for Micro Units (CGFMU).",
        "interest_subvention": "Bank specific (approx 8.5% - 11.5% p.a.)",
        "margin_money_percentage_general": 15.0,
        "margin_money_percentage_special": 10.0,
        "stacking_eligible": True,
        "stacking_notes": "Eligible for state-level interest refund schemes (e.g., Annasaheb Patil in Maharashtra).",
        "repayment_period_months": 60,
        "moratorium_months": 3,
        "required_documents": ["AADHAAR", "PAN", "BUSINESS_ADDRESS_PROOF", "BANK_STATEMENT_6_MONTHS", "QUOTATION_FOR_MACHINERY_ANIMALS"],
        "official_portal_url": "https://www.mudra.org.in/",
        "guidelines_pdf_url": "https://www.mudra.org.in/Offerings",
        "effective_from": "2015-04-08",
        "effective_to": None,
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2015-04-08",
        "source_updated_at": "2024-03-20",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_NLM_EDP",
        "code": "NLM_EDP",
        "name": "National Livestock Mission (NLM) - Entrepreneurship Development Programme",
        "official_name": "National Livestock Mission - Sub-Mission on Breed and Feed Development (EDP Component)",
        "scheme_tier": "CENTRAL",
        "state_name": "Central (Pan-India)",
        "funding_pattern": "100% Central Ministry DAHD Funding",
        "category": "Central Sector Scheme",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "implementing_agency": "Department of Animal Husbandry & Dairying (DAHD)",
        "source_id": "SRC_DAHD",
        "target_beneficiaries": ["Individual Entrepreneurs", "FPOs", "SHGs", "Farmers", "Co-operatives"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women"],
        "occupation_criteria": ["Farmer", "Dairy/Poultry/Sheep Farmer", "Rural Entrepreneur"],
        "business_types": ["Poultry Farming", "Sheep & Goat Breeding Unit", "Pig Breeding Unit", "Fodder Production & Silage Unit"],
        "education_criteria": "Livestock training / practical experience certificate preferred",
        "min_loan_amount": 200000.0,
        "max_loan_amount": 50000000.0,
        "subsidy_percentage_general_rural": 50.0,
        "subsidy_percentage_special_rural": 50.0,
        "subsidy_description": "50% capital back-ended subsidy (up to ₹25 Lakh for sheep/goat/poultry breeding; up to ₹50 Lakh for fodder units) disbursed in two equal installments.",
        "interest_subvention": "Normal Bank Lending Rates",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 10.0,
        "stacking_eligible": True,
        "stacking_notes": "Can stack with AHIDF interest subvention on remaining term loan.",
        "repayment_period_months": 84,
        "moratorium_months": 12,
        "required_documents": ["AADHAAR", "PAN", "LAND_OWNERSHIP_OR_LEASE_DOCUMENT", "DETAILED_PROJECT_REPORT", "TRAINING_CERTIFICATE", "BANK_SANCTION_LETTER"],
        "official_portal_url": "https://nlm.udyamimitra.in/",
        "guidelines_pdf_url": "https://dahd.nic.in/schemes/programmes/nlm",
        "effective_from": "2021-07-14",
        "effective_to": "2026-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2021-07-14",
        "source_updated_at": "2024-02-15",
        "verification_method": "OFFICIAL_GAZETTE",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_AHIDF",
        "code": "AHIDF",
        "name": "Animal Husbandry Infrastructure Development Fund (AHIDF)",
        "official_name": "Animal Husbandry Infrastructure Development Fund (AHIDF)",
        "scheme_tier": "CENTRAL",
        "state_name": "Central (Pan-India)",
        "funding_pattern": "100% Central Government (DAHD + SIDBI)",
        "category": "Central Sector Scheme",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "implementing_agency": "DAHD / SIDBI / Scheduled Commercial Banks",
        "source_id": "SRC_DAHD",
        "target_beneficiaries": ["Individual Entrepreneurs", "MSME Units", "Dairy Co-operatives", "FPOs"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women"],
        "occupation_criteria": ["Dairy Entrepreneur", "Meat Processor", "Animal Feed Manufacturer", "FPO"],
        "business_types": ["Dairy Processing Plant", "Value Added Dairy Products", "Meat Processing", "Animal Feed Plant"],
        "education_criteria": "Relevant technical / business background",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 500000000.0,
        "subsidy_percentage_general_rural": 0.0,
        "subsidy_percentage_special_rural": 0.0,
        "subsidy_description": "3% Interest Subvention for up to 8 years on bank loan + credit guarantee coverage up to 25% of total loan under Credit Guarantee Fund.",
        "interest_subvention": "3.0% interest subvention for 8 years",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 10.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows co-financing with state-level capital subsidies.",
        "repayment_period_months": 96,
        "moratorium_months": 24,
        "required_documents": ["AADHAAR", "PAN", "DPR_DETAILED_PROJECT_REPORT", "LAND_DOCUMENT_7_12", "POLLUTION_NOC", "BANK_STATEMENT"],
        "official_portal_url": "https://ahidf.udyamimitra.in/",
        "guidelines_pdf_url": "https://dahd.nic.in/schemes/programmes/ahidf",
        "effective_from": "2020-06-24",
        "effective_to": "2026-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2020-06-24",
        "source_updated_at": "2024-02-15",
        "verification_method": "OFFICIAL_GAZETTE",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_STANDUP_INDIA",
        "code": "STANDUP_INDIA",
        "name": "Stand-Up India Scheme",
        "official_name": "Stand-Up India Scheme for SC/ST and Women Entrepreneurs",
        "scheme_tier": "CENTRAL",
        "state_name": "Central (Pan-India)",
        "funding_pattern": "100% Central Ministry of Finance (DFS / SIDBI)",
        "category": "Central Sector Scheme",
        "ministry": "Ministry of Finance",
        "implementing_agency": "SIDBI / Scheduled Commercial Banks",
        "source_id": "SRC_STANDUP",
        "target_beneficiaries": ["Women Entrepreneurs", "SC Entrepreneurs", "ST Entrepreneurs"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["SC", "ST", "Women"],
        "occupation_criteria": ["First-Time Borrower", "Entrepreneur", "Artisan", "Greenfield Enterprise Promoter"],
        "business_types": ["Manufacturing", "Services", "Agri-Allied Enterprises", "Trading Enterprise"],
        "education_criteria": "None mandatory",
        "min_loan_amount": 1000000.0,
        "max_loan_amount": 10000000.0,
        "subsidy_percentage_general_rural": 0.0,
        "subsidy_percentage_special_rural": 0.0,
        "subsidy_description": "Bank loan between ₹10 Lakh to ₹1 Crore for greenfield enterprise. Margin money requirement up to 15% (can be converged with eligible central/state subsidies).",
        "interest_subvention": "Lowest applicable rate for the category (Base Rate/MCLR + 3% + Tenor Premium)",
        "margin_money_percentage_general": 15.0,
        "margin_money_percentage_special": 15.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows margin money convergence with central and state subsidy schemes up to 15%.",
        "repayment_period_months": 84,
        "moratorium_months": 18,
        "required_documents": ["AADHAAR", "PAN", "CASTE_CERTIFICATE_OR_WOMAN_ID", "PROJECT_REPORT", "RENT_OR_LAND_AGREEMENT", "BANK_STATEMENT"],
        "official_portal_url": "https://www.standupmitra.in/",
        "guidelines_pdf_url": "https://www.standupmitra.in/Home/SUISchemes",
        "effective_from": "2016-04-05",
        "effective_to": "2026-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2016-04-05",
        "source_updated_at": "2024-01-10",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_AIF",
        "code": "AIF",
        "name": "Agriculture Infrastructure Fund (AIF)",
        "official_name": "Central Sector Scheme of Financing Facility under Agriculture Infrastructure Fund",
        "scheme_tier": "CENTRAL",
        "state_name": "Central (Pan-India)",
        "funding_pattern": "100% Central Ministry of Agriculture",
        "category": "Central Sector Scheme",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "implementing_agency": "Department of Agriculture & Farmers Welfare (DA&FW)",
        "source_id": "SRC_AIF",
        "target_beneficiaries": ["Primary Agricultural Credit Societies (PACS)", "Marketing Co-operatives", "FPOs", "SHGs", "Farmers", "Agri-Entrepreneurs"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women"],
        "occupation_criteria": ["Farmer", "Agri-Entrepreneur", "FPO Member", "Custom Hiring Operator"],
        "business_types": ["Cold Storage", "Silos / Warehouses", "Sorting & Grading Units", "Custom Hiring Center", "Solar Farm Infrastructure"],
        "education_criteria": "None mandatory",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 20000000.0,
        "subsidy_percentage_general_rural": 0.0,
        "subsidy_percentage_special_rural": 0.0,
        "subsidy_description": "3% per annum interest subvention up to a loan limit of ₹2 Crore for a maximum period of 7 years, plus CGTMSE fee reimbursement.",
        "interest_subvention": "3.0% interest subvention for 7 years",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 10.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows dual-benefit stacking with PMFME or state capital subsidy schemes.",
        "repayment_period_months": 84,
        "moratorium_months": 12,
        "required_documents": ["AADHAAR", "PAN", "LAND_DOCUMENT_OR_LEASE", "PROJECT_REPORT_DPR", "BANK_STATEMENT"],
        "official_portal_url": "https://agriinfra.dac.gov.in/",
        "guidelines_pdf_url": "https://agriinfra.dac.gov.in/Home/Guidelines",
        "effective_from": "2020-07-08",
        "effective_to": "2032-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2020-07-08",
        "source_updated_at": "2024-03-01",
        "verification_method": "OFFICIAL_GAZETTE",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_MICRO_FINANCE",
        "code": "MFS",
        "name": "State Channelizing Agency Micro Finance Scheme (MFS)",
        "official_name": "SCA/CA Concessional Micro Credit Scheme for Marginalized Beneficiaries",
        "scheme_tier": "CENTRAL",
        "state_name": "Central (Pan-India)",
        "funding_pattern": "90% Concessional SCA Loan : 10% Beneficiary Margin",
        "category": "Concessional Credit Scheme",
        "ministry": "Ministry of Social Justice and Empowerment (MoSJE)",
        "implementing_agency": "State Channelizing Agencies (SCAs) / Channelizing Agencies (CAs)",
        "source_id": "SRC_MOSJE",
        "target_beneficiaries": ["Marginalized Rural Youth", "Micro-Entrepreneurs", "SHG Members", "OBC/SC/ST Beneficiaries"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 60,
        "max_annual_income": 300000.0,
        "category_criteria": ["General", "OBC", "SC", "ST", "Minority", "Women"],
        "occupation_criteria": ["Farmer", "Artisan", "Rural Entrepreneur", "Small Vendor"],
        "business_types": ["Dairy", "Poultry", "Retail Shop", "Handicrafts", "Services", "Tailoring", "Agro-inputs"],
        "education_criteria": "Self-declaration of skill",
        "min_loan_amount": 10000.0,
        "max_loan_amount": 125000.0,
        "subsidy_percentage_general_rural": 0.0,
        "subsidy_percentage_special_rural": 0.0,
        "subsidy_description": "Concessional credit at 6.5% p.a. for project cost up to ₹1.40 Lakh with 10% margin money.",
        "interest_subvention": "Fixed 6.5% p.a. concessional interest rate",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 10.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows repayment over 3 years including 3-month moratorium.",
        "repayment_period_months": 36,
        "moratorium_months": 3,
        "required_documents": ["AADHAAR", "PAN", "CASTE_CERTIFICATE_IF_APPLICABLE", "INCOME_CERTIFICATE", "BANK_STATEMENT"],
        "official_portal_url": "https://socialjustice.gov.in/",
        "guidelines_pdf_url": "https://socialjustice.gov.in/schemes/micro-finance",
        "effective_from": "2015-04-01",
        "effective_to": "2026-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2015-04-01",
        "source_updated_at": "2024-01-15",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_TERM_LOAN",
        "code": "TLS",
        "name": "State Channelizing Agency Term Loan Scheme (TLS)",
        "official_name": "SCA/CA Concessional Term Loan Scheme for Income-Generating Activities",
        "scheme_tier": "CENTRAL",
        "state_name": "Central (Pan-India)",
        "funding_pattern": "90% Concessional SCA Loan : 10% Beneficiary Margin",
        "category": "Concessional Credit Scheme",
        "ministry": "Ministry of Social Justice and Empowerment (MoSJE)",
        "implementing_agency": "State Channelizing Agencies (SCAs) / Channelizing Agencies (CAs)",
        "source_id": "SRC_MOSJE",
        "target_beneficiaries": ["Marginalized Entrepreneurs", "Rural Youth", "OBC/SC/ST Entrepreneurs", "Women Enterprises"],
        "state_applicability": ["ALL"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 60,
        "max_annual_income": 300000.0,
        "category_criteria": ["General", "OBC", "SC", "ST", "Minority", "Women"],
        "occupation_criteria": ["Rural Entrepreneur", "Farmer", "Food Processor", "Workshop Owner"],
        "business_types": ["Agro-Processing", "Dairy Chilling Unit", "Poultry Farm", "Cold Storage", "Custom Hiring", "Rural Retail"],
        "education_criteria": "8th Standard Pass preferred",
        "min_loan_amount": 125001.0,
        "max_loan_amount": 4500000.0,
        "subsidy_percentage_general_rural": 0.0,
        "subsidy_percentage_special_rural": 0.0,
        "subsidy_description": "Concessional credit at 8.0% p.a. for project cost between ₹1.40 Lakh and ₹50.00 Lakh with 10% margin money.",
        "interest_subvention": "Fixed 8.0% p.a. concessional interest rate",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 10.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows repayment over 7 years including 6-month moratorium.",
        "repayment_period_months": 84,
        "moratorium_months": 6,
        "required_documents": ["AADHAAR", "PAN", "PROJECT_REPORT_DPR", "CASTE_CERTIFICATE_IF_APPLICABLE", "INCOME_CERTIFICATE", "BANK_STATEMENT"],
        "official_portal_url": "https://socialjustice.gov.in/",
        "guidelines_pdf_url": "https://socialjustice.gov.in/schemes/term-loan",
        "effective_from": "2015-04-01",
        "effective_to": "2026-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2015-04-01",
        "source_updated_at": "2024-01-15",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    # --- State Government Schemes ---
    {
        "scheme_id": "SCHEME_MH_ANNASAHEB_PATIL",
        "code": "MH_ANNASAHEB_PATIL",
        "name": "Annasaheb Patil Interest Reimbursement Scheme (IR15 - Maharashtra)",
        "official_name": "Annasaheb Patil Arthik-magas Vikas Mahamandal - Vyaj Partava Yojana",
        "scheme_tier": "STATE",
        "state_name": "Maharashtra",
        "funding_pattern": "100% Maharashtra State Government Budget",
        "category": "State Government Scheme",
        "ministry": "Skill Development, Employment and Entrepreneurship Dept, Govt. of Maharashtra",
        "implementing_agency": "Annasaheb Patil Arthik-magas Vikas Mahamandal (MahaSwayam)",
        "source_id": "SRC_MH_GOV",
        "target_beneficiaries": ["Rural Youth", "Farmers", "First-Generation Micro-Entrepreneurs in Maharashtra"],
        "state_applicability": ["Maharashtra"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 50,
        "max_annual_income": 800000.0,
        "category_criteria": ["General", "OBC", "EWS", "Women"],
        "occupation_criteria": ["Farmer", "Unemployed Youth", "Micro-Entrepreneur"],
        "business_types": ["Dairy Farming", "Poultry Farming", "Food Processing", "Rural Transport", "Retail Enterprise", "Agro-Services"],
        "education_criteria": "None mandatory",
        "min_loan_amount": 100000.0,
        "max_loan_amount": 1500000.0,
        "subsidy_percentage_general_rural": 0.0,
        "subsidy_percentage_special_rural": 0.0,
        "subsidy_description": "100% Interest reimbursement on bank loans up to ₹15 Lakh (maximum 12% p.a. interest deposited directly into beneficiary bank account for up to 5 years, max limit ₹4.5 Lakh total interest).",
        "interest_subvention": "100% Interest Subvention (up to 12% p.a. max ₹4.5 Lakh total interest)",
        "margin_money_percentage_general": 5.0,
        "margin_money_percentage_special": 5.0,
        "stacking_eligible": True,
        "stacking_notes": "Can be stacked on top of Mudra Kishore / Tarun or standard bank term loans.",
        "repayment_period_months": 60,
        "moratorium_months": 3,
        "required_documents": ["AADHAAR", "PAN", "DOMICILE_MAHARASHTRA", "INCOME_CERTIFICATE_TEHSILDAR", "BANK_SANCTION_LETTER", "UDYAM_AADHAAR"],
        "official_portal_url": "https://mahaswayam.gov.in/",
        "guidelines_pdf_url": "https://annasahebpatil.in/",
        "effective_from": "2018-03-01",
        "effective_to": "2028-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2018-03-01",
        "source_updated_at": "2024-06-15",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_MH_SMART_AGRI",
        "code": "MH_SMART_AGRI",
        "name": "Balasaheb Thackeray SMART Agribusiness & Livestock Project",
        "official_name": "Hon. Balasaheb Thackeray Agribusiness and Rural Transformation (SMART) Project",
        "scheme_tier": "STATE",
        "state_name": "Maharashtra",
        "funding_pattern": "70% World Bank + 30% Maharashtra State Govt",
        "category": "State Supported Project",
        "ministry": "Department of Agriculture, Govt. of Maharashtra",
        "implementing_agency": "SMART Project Implementation Unit / Dept. of Agriculture MH",
        "source_id": "SRC_MH_SMART",
        "target_beneficiaries": ["Community Based Organizations", "FPOs", "Dairy/Goat Producer Groups", "Women SHGs"],
        "state_applicability": ["Maharashtra"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women"],
        "occupation_criteria": ["Farmer", "Dairy Producer Group Member", "Livestock Farmer"],
        "business_types": ["Dairy Processing Plant", "Goat & Poultry Value Chain", "Agro-Processing", "Cold Storage", "Direct Marketing Infrastructure"],
        "education_criteria": "None mandatory",
        "min_loan_amount": 500000.0,
        "max_loan_amount": 10000000.0,
        "subsidy_percentage_general_rural": 60.0,
        "subsidy_percentage_special_rural": 60.0,
        "subsidy_description": "60% matching grant for collective farmer enterprises, agro-processing, livestock value chains and chilling infrastructure (up to ₹1 Crore grant).",
        "interest_subvention": "Direct Project Capital Grant",
        "margin_money_percentage_general": 20.0,
        "margin_money_percentage_special": 20.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows co-financing with bank loans under Agriculture Infrastructure Fund (AIF).",
        "repayment_period_months": 84,
        "moratorium_months": 12,
        "required_documents": ["AADHAAR", "PAN", "CBO_FPO_REGISTRATION", "DETAILED_PROJECT_REPORT", "LAND_DOCUMENT_7_12", "BANK_STATEMENT"],
        "official_portal_url": "https://smart-mh.org/",
        "guidelines_pdf_url": "https://smart-mh.org/guidelines",
        "effective_from": "2020-09-01",
        "effective_to": "2027-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2020-09-01",
        "source_updated_at": "2024-04-10",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_UP_MMGRY",
        "code": "UP_MMGRY",
        "name": "Mukhyamantri Gramodyog Rozgar Yojana (MMGRY - Uttar Pradesh)",
        "official_name": "Uttar Pradesh Mukhyamantri Gramodyog Rozgar Yojana",
        "scheme_tier": "STATE",
        "state_name": "Uttar Pradesh",
        "funding_pattern": "100% Uttar Pradesh State Budget",
        "category": "State Government Scheme",
        "ministry": "Khadi and Village Industries Board, Govt. of Uttar Pradesh",
        "implementing_agency": "UP State Khadi & Village Industries Board (UPKVIB)",
        "source_id": "SRC_UP_GOV",
        "target_beneficiaries": ["Rural Youth", "Artisans", "Women", "Ex-Servicemen", "SC/ST/OBC in UP"],
        "state_applicability": ["Uttar Pradesh"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 50,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women", "Minority"],
        "occupation_criteria": ["Unemployed Youth", "Artisan", "Rural Entrepreneur", "Farmer"],
        "business_types": ["Manufacturing", "Food Processing", "Rural Workshop", "Dairy Products Processing", "Agro-Enterprise"],
        "education_criteria": "8th Pass preferred",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 1000000.0,
        "subsidy_percentage_general_rural": 0.0,
        "subsidy_percentage_special_rural": 0.0,
        "subsidy_description": "100% interest subsidy for SC/ST/OBC/Women/Minority on bank loans up to ₹10 Lakh for 3 years; 4% interest subvention for General category men.",
        "interest_subvention": "100% Interest Subsidy for SC/ST/Women/OBC; 4% Subvention for General",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 5.0,
        "stacking_eligible": True,
        "stacking_notes": "State top-up scheme operating alongside central MSME credit facilities.",
        "repayment_period_months": 60,
        "moratorium_months": 6,
        "required_documents": ["AADHAAR", "PAN", "DOMICILE_UP", "PROJECT_REPORT", "CASTE_CERTIFICATE_IF_APPLICABLE", "EDUCATIONAL_PROOF", "BANK_PASSBOOK"],
        "official_portal_url": "http://upkvib.gov.in/",
        "guidelines_pdf_url": "https://msme.up.gov.in/",
        "effective_from": "2017-06-01",
        "effective_to": "2027-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2017-06-01",
        "source_updated_at": "2024-03-15",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_GJ_AGRO_MSME",
        "code": "GJ_AGRO_MSME",
        "name": "Gujarat Agro-Industrial MSME Capital & Interest Subsidy Scheme",
        "official_name": "Gujarat Comprehensive Agriculture Business Policy Scheme",
        "scheme_tier": "STATE",
        "state_name": "Gujarat",
        "funding_pattern": "100% Gujarat State Government Budget",
        "category": "State Government Scheme",
        "ministry": "Agriculture, Farmers Welfare & Co-operation Dept, Govt. of Gujarat",
        "implementing_agency": "Gujarat Agro Industries Corporation (GAIC) / i-Khedut Portal",
        "source_id": "SRC_GJ_GOV",
        "target_beneficiaries": ["Agro-Entrepreneurs", "Dairy Farmers", "Food Processing Units", "FPOs in Gujarat"],
        "state_applicability": ["Gujarat"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women"],
        "occupation_criteria": ["Farmer", "Agro-Processor", "Dairy Entrepreneur"],
        "business_types": ["Dairy Processing Plant", "Flour Mill", "Oil Extraction", "Cold Chain Infrastructure", "Sorting & Packaging Unit"],
        "education_criteria": "None mandatory",
        "min_loan_amount": 200000.0,
        "max_loan_amount": 10000000.0,
        "subsidy_percentage_general_rural": 25.0,
        "subsidy_percentage_special_rural": 30.0,
        "subsidy_description": "25% capital subsidy up to ₹25 Lakh on plant/machinery + 5% interest subsidy for 5 years for agro & dairy units.",
        "interest_subvention": "5.0% interest subsidy for 5 years",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 10.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows co-financing and interest subsidy stacking with central AIF scheme.",
        "repayment_period_months": 84,
        "moratorium_months": 12,
        "required_documents": ["AADHAAR", "PAN", "GUJARAT_DOMICILE_OR_LAND_RECORD_7_12", "PROJECT_REPORT", "BANK_SANCTION_LETTER", "UDYAM_REGISTRATION"],
        "official_portal_url": "https://ikhedut.gujarat.gov.in/",
        "guidelines_pdf_url": "https://gaic.gujarat.gov.in/",
        "effective_from": "2021-04-01",
        "effective_to": "2026-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2021-04-01",
        "source_updated_at": "2024-02-20",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_KA_CMEGP",
        "code": "KA_CMEGP",
        "name": "Karnataka Chief Minister's Employment Generation Programme (CMEGP)",
        "official_name": "Karnataka Chief Minister's Employment Generation Programme (CMEGP)",
        "scheme_tier": "STATE",
        "state_name": "Karnataka",
        "funding_pattern": "100% Karnataka State Government Budget",
        "category": "State Government Scheme",
        "ministry": "Department of Commerce & Industries, Govt. of Karnataka",
        "implementing_agency": "District Industries Centre (DIC) / Karnataka KVIC",
        "source_id": "SRC_KA_GOV",
        "target_beneficiaries": ["Rural Youth", "Women", "SC/ST/OBC in Karnataka"],
        "state_applicability": ["Karnataka"],
        "district_applicability": ["ALL"],
        "min_age": 18,
        "max_age": 55,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women", "Minority"],
        "occupation_criteria": ["Unemployed Youth", "Artisan", "Rural Entrepreneur", "Farmer"],
        "business_types": ["Manufacturing", "Services", "Food Processing", "Rural Workshop", "Dairy Value Addition"],
        "education_criteria": "8th Pass preferred",
        "min_loan_amount": 50000.0,
        "max_loan_amount": 1000000.0,
        "subsidy_percentage_general_rural": 25.0,
        "subsidy_percentage_special_rural": 35.0,
        "subsidy_description": "25% subsidy for general rural; 35% subsidy for SC/ST/OBC/Women up to project cost of ₹10 Lakh.",
        "interest_subvention": "Standard Bank Rates with State Subsidy",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 5.0,
        "stacking_eligible": False,
        "stacking_notes": "Standalone state counterpart of PMEGP for Karnataka rural youth.",
        "repayment_period_months": 60,
        "moratorium_months": 6,
        "required_documents": ["AADHAAR", "PAN", "KARNATAKA_DOMICILE", "PROJECT_REPORT", "CASTE_INCOME_CERTIFICATE", "EDUCATIONAL_PROOF"],
        "official_portal_url": "https://cmegp.kar.nic.in/",
        "guidelines_pdf_url": "https://cmegp.kar.nic.in/guidelines",
        "effective_from": "2019-04-01",
        "effective_to": "2027-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2019-04-01",
        "source_updated_at": "2024-05-01",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    },
    {
        "scheme_id": "SCHEME_TN_NEEDS",
        "code": "TN_NEEDS",
        "name": "Tamil Nadu New Entrepreneur-cum-Enterprise Development Scheme (NEEDS)",
        "official_name": "New Entrepreneur-cum-Enterprise Development Scheme (NEEDS) Tamil Nadu",
        "scheme_tier": "STATE",
        "state_name": "Tamil Nadu",
        "funding_pattern": "100% Tamil Nadu State Government Budget",
        "category": "State Government Scheme",
        "ministry": "Micro, Small and Medium Enterprises Department, Govt. of Tamil Nadu",
        "implementing_agency": "District Industries Centre (DIC) / TIIC Tamil Nadu",
        "source_id": "SRC_TN_GOV",
        "target_beneficiaries": ["First-Generation Graduate Entrepreneurs in Tamil Nadu", "Women", "SC/ST/BC/MBC"],
        "state_applicability": ["Tamil Nadu"],
        "district_applicability": ["ALL"],
        "min_age": 21,
        "max_age": 45,
        "max_annual_income": None,
        "category_criteria": ["General", "OBC", "SC", "ST", "Women"],
        "occupation_criteria": ["First-Time Graduate Entrepreneur", "Rural MSME Promoter"],
        "business_types": ["Manufacturing", "Services", "Agro-Processing", "Dairy Processing Plant", "Engineering Workshop"],
        "education_criteria": "Diploma / Degree / ITI qualification mandatory",
        "min_loan_amount": 1000000.0,
        "max_loan_amount": 50000000.0,
        "subsidy_percentage_general_rural": 25.0,
        "subsidy_percentage_special_rural": 25.0,
        "subsidy_description": "25% project cost capital subsidy (maximum ₹75 Lakh) + 3% interest subvention for entire repayment tenure.",
        "interest_subvention": "3.0% Interest Subvention for entire tenure",
        "margin_money_percentage_general": 10.0,
        "margin_money_percentage_special": 5.0,
        "stacking_eligible": True,
        "stacking_notes": "Allows co-funding with TIIC term loans and commercial bank credit.",
        "repayment_period_months": 84,
        "moratorium_months": 12,
        "required_documents": ["AADHAAR", "PAN", "DEGREE_DIPLOMA_CERTIFICATE", "PROJECT_REPORT", "COMMUNITY_CERTIFICATE", "BANK_STATEMENT"],
        "official_portal_url": "https://msmeonline.tn.gov.in/needs/",
        "guidelines_pdf_url": "https://www.editn.in/needs",
        "effective_from": "2012-07-01",
        "effective_to": "2027-03-31",
        "superseded_by": None,
        "last_verified_at": "2026-08-01",
        "source_published_at": "2012-07-01",
        "source_updated_at": "2024-03-10",
        "verification_method": "MINISTRY_PORTAL",
        "status": "ACTIVE"
    }
]

BUSINESS_TEMPLATES: List[Dict] = [
    {
        "business_id": "BIZ_DAIRY_FARMING",
        "code": "DAIRY_FARMING",
        "name": "Dairy Farming (2–5 Crossbred Cows/Buffaloes Unit)",
        "name_hi": "डेयरी फार्मिंग (2-5 दुधारू पशु यूनिट)",
        "name_mr": "डेअरी फार्मिंग (२ ते ५ संकरित गायी/म्हशी युनिट)",
        "sector": "Livestock & Allied Agriculture",
        "description": "Establishment of a small-scale commercial dairy unit with high-yield milch animals, stall-fed management, green fodder cultivation, and direct milk supply to local co-operatives or private dairies.",
        "min_investment": 120000.0,
        "typical_investment": 220000.0,
        "max_investment": 600000.0,
        "typical_own_contribution_pct": 10.0,
        "equipment_needed": ["Milking Cans & Buckets", "Chaff Cutter", "Shed Flooring & Mangers", "Water Supply Tank & Pipes", "Cooling Equipment"],
        "working_capital_months": 3,
        "typical_revenue_monthly": 42000.0,
        "typical_expenses_monthly": 24000.0,
        "profit_margin_range": "32% - 45%",
        "break_even_months": 9,
        "key_risks": [
            "Animal disease / sudden mortality without insurance",
            "Fodder price spike during dry summer months",
            "Fluctuation in co-operative fat/SNF procurement rates",
            "Delayed breeding cycle / extended dry period"
        ],
        "mitigation_strategies": [
            "Mandatory livestock insurance under government-subsidized animal insurance scheme",
            "Silage making & multi-cut green fodder cultivation on leased/own land",
            "Clean milk production practices to maximize fat/SNF bonus",
            "Regular veterinary checkups and timely artificial insemination"
        ],
        "required_documents": ["AADHAAR", "PAN", "LAND_DOCUMENT_7_12_OR_NOC", "BANK_PASSBOOK", "QUOTATION_FOR_MILCH_ANIMALS", "MILK_SUPPLY_INTENT_LETTER"],
        "default_assumptions": {
            "parameters": [
                {
                    "parameter": "num_animals",
                    "label": "Number of Animals",
                    "value": 2,
                    "unit": "animals",
                    "minimum": 1,
                    "maximum": 10,
                    "source": "NABARD Model Bankable Dairy Project",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "animal_cost_inr",
                    "label": "Cost per Animal",
                    "value": 85000,
                    "unit": "₹ / animal",
                    "minimum": 50000,
                    "maximum": 130000,
                    "source": "State Livestock Market Benchmark",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "shed_and_equipment_cost",
                    "label": "Shed & Chaff Cutter Cost",
                    "value": 50000,
                    "unit": "₹ total",
                    "minimum": 20000,
                    "maximum": 150000,
                    "source": "Rural Infrastructure Standard Estimates",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "milk_yield_per_day",
                    "label": "Average Daily Milk Yield",
                    "value": 13.0,
                    "unit": "Liters / animal / day",
                    "minimum": 8.0,
                    "maximum": 24.0,
                    "source": "DAHD Livestock Performance Metrics",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "milk_selling_price",
                    "label": "Farmgate Milk Selling Price",
                    "value": 42.0,
                    "unit": "₹ / Liter",
                    "minimum": 32.0,
                    "maximum": 58.0,
                    "source": "District Milk Producers Co-op Society Rates",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "feed_cost_per_day",
                    "label": "Feed & Fodder Cost per Animal",
                    "value": 180.0,
                    "unit": "₹ / animal / day",
                    "minimum": 120.0,
                    "maximum": 280.0,
                    "source": "ICAR-NDRI Feed Management Guide",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "vet_and_medicines_monthly",
                    "label": "Veterinary & Medicine Cost",
                    "value": 1200.0,
                    "unit": "₹ / month",
                    "minimum": 500.0,
                    "maximum": 3500.0,
                    "source": "Local Veterinary Dispensary Averages",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "electricity_water_monthly",
                    "label": "Electricity & Miscellaneous",
                    "value": 1000.0,
                    "unit": "₹ / month",
                    "minimum": 400.0,
                    "maximum": 3000.0,
                    "source": "Rural Utility Tariff Schedule",
                    "last_updated": "2026-08-01"
                }
            ]
        }
    },
    {
        "business_id": "BIZ_COLD_PRESSED_OIL",
        "code": "COLD_PRESSED_OIL",
        "name": "Cold-Pressed Edible Oil Extraction Unit (Lakdi Ghani / Kachi Ghani)",
        "name_hi": "लकड़ी घानी तेल निष्कर्षण यूनिट",
        "name_mr": "लाकडी घाणा तेल प्रक्रिया उद्योग",
        "sector": "Agro-Processing & Food Manufacturing",
        "description": "Production and retail packaging of unrefined, chemical-free cold pressed edible oils (Groundnut, Mustard, Sesame, Sunflower, Coconut) targeting health-conscious consumers and local village markets.",
        "min_investment": 250000.0,
        "typical_investment": 450000.0,
        "max_investment": 1200000.0,
        "typical_own_contribution_pct": 10.0,
        "equipment_needed": ["Rotary Wood Press (Lakdi Ghani Machine)", "Seed Cleaner & Destoner", "Oil Filter Press", "Bottle Filling & Capping Machine", "FSSAI Compliant Storage Cans"],
        "working_capital_months": 2,
        "typical_revenue_monthly": 85000.0,
        "typical_expenses_monthly": 52000.0,
        "profit_margin_range": "28% - 38%",
        "break_even_months": 8,
        "key_risks": [
            "Seasonal raw oilseed price volatility",
            "Electricity supply interruption in rural feeders",
            "Marketing & consumer reach outside immediate village"
        ],
        "mitigation_strategies": [
            "Advance procurement contract with local farmers during harvest season",
            "Installation of a 5 HP solar/backup grid supply",
            "Direct sales via local weekly Haats, Kirana stores, and WhatsApp groups"
        ],
        "required_documents": ["AADHAAR", "PAN", "FSSAI_REGISTRATION", "UDYAM_MSME", "PROJECT_REPORT", "ELECTRICITY_CONNECTION_PROOF"],
        "default_assumptions": {
            "parameters": [
                {
                    "parameter": "daily_raw_seed_kg",
                    "label": "Raw Oilseed Processed per Day",
                    "value": 60,
                    "unit": "kg / day",
                    "minimum": 25,
                    "maximum": 200,
                    "source": "MoFPI PMFME Model DPR for Oil Processing",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "oil_recovery_pct",
                    "label": "Oil Recovery Rate",
                    "value": 40.0,
                    "unit": "% of seed weight",
                    "minimum": 32.0,
                    "maximum": 46.0,
                    "source": "CFTRI Oil Extraction Benchmark",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "raw_seed_cost_per_kg",
                    "label": "Average Raw Seed Cost",
                    "value": 85.0,
                    "unit": "₹ / kg",
                    "minimum": 60.0,
                    "maximum": 120.0,
                    "source": "APMC Mandi Wholesale Rates",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "oil_selling_price_per_liter",
                    "label": "Pure Cold Pressed Oil Selling Price",
                    "value": 280.0,
                    "unit": "₹ / Liter",
                    "minimum": 210.0,
                    "maximum": 380.0,
                    "source": "Regional Market Retail Price Benchmark",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "oilcake_selling_price_per_kg",
                    "label": "Oil Cake (Khali) Byproduct Price",
                    "value": 32.0,
                    "unit": "₹ / kg (Sold as cattle feed)",
                    "minimum": 22.0,
                    "maximum": 42.0,
                    "source": "Local Cattle Feed Market Price",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "packaging_and_electricity_monthly",
                    "label": "Electricity & Packaging Costs",
                    "value": 6500.0,
                    "unit": "₹ / month",
                    "minimum": 3000.0,
                    "maximum": 15000.0,
                    "source": "Standard Operating Expense Baseline",
                    "last_updated": "2026-08-01"
                }
            ]
        }
    },
    {
        "business_id": "BIZ_BROILER_POULTRY",
        "code": "POULTRY_FARMING",
        "name": "Broiler Poultry Farming (Contract / Independent 1,000 Birds Batch)",
        "name_hi": "ब्रायलर पोल्ट्री फार्मिंग (1000 पक्षी यूनिट)",
        "name_mr": "ब्रॉयलर पोल्ट्री व्यवसाय (१,००० पक्षी युनिट)",
        "sector": "Livestock & Allied Agriculture",
        "description": "Commercial broiler production on environmentally controlled or open-sided poultry sheds with 6 cycles per year, high feed conversion ratio (FCR), and institutional buyer tie-ups.",
        "min_investment": 180000.0,
        "typical_investment": 320000.0,
        "max_investment": 800000.0,
        "typical_own_contribution_pct": 10.0,
        "equipment_needed": ["Brooders & Heaters", "Automatic Drinkers & Feeders", "Curtains & Ventilation Fans", "Fogger System for Summer", "Weighing Scales"],
        "working_capital_months": 2,
        "typical_revenue_monthly": 62000.0,
        "typical_expenses_monthly": 38000.0,
        "profit_margin_range": "24% - 35%",
        "break_even_months": 7,
        "key_risks": [
            "Disease outbreak (Ranikhet, Bird Flu)",
            "Extreme heat mortality in summer",
            "Wholesale chicken meat rate collapse"
        ],
        "mitigation_strategies": [
            "Strict biosecurity and vaccination calendar",
            "Foggers and cool roof thatch installation",
            "Contract farming integration with established poultry firms (providing chicks, feed, and buyback guarantee)"
        ],
        "required_documents": ["AADHAAR", "PAN", "GRAM_PANCHAYAT_NOC", "LAND_DOCUMENT", "INTEGRATION_COMPANY_AGREEMENT"],
        "default_assumptions": {
            "parameters": [
                {
                    "parameter": "batch_capacity",
                    "label": "Birds per Batch",
                    "value": 1000,
                    "unit": "birds / batch",
                    "minimum": 500,
                    "maximum": 5000,
                    "source": "NABARD Broiler Farming Bankable Scheme",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "cycles_per_year",
                    "label": "Batches (Cycles) per Year",
                    "value": 6,
                    "unit": "cycles / year",
                    "minimum": 4,
                    "maximum": 7,
                    "source": "Poultry Industry Standard Practice",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "growing_charges_or_profit_per_kg",
                    "label": "Growing Charges / Net Profit per kg Live Bird",
                    "value": 10.5,
                    "unit": "₹ / kg",
                    "minimum": 7.0,
                    "maximum": 16.0,
                    "source": "State Poultry Integration Association Rates",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "average_live_weight_kg",
                    "label": "Average Live Bird Weight at 40 Days",
                    "value": 2.2,
                    "unit": "kg / bird",
                    "minimum": 1.8,
                    "maximum": 2.6,
                    "source": "CARI Avian Research Standard",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "mortality_pct",
                    "label": "Normal Mortality Rate",
                    "value": 4.0,
                    "unit": "% of batch",
                    "minimum": 2.0,
                    "maximum": 9.0,
                    "source": "Veterinary Science Field Data",
                    "last_updated": "2026-08-01"
                }
            ]
        }
    },
    {
        "business_id": "BIZ_FLOUR_SPICE_MILL",
        "code": "FLOUR_SPICE_MILL",
        "name": "Custom Flour, Pulse & Spice Grinding Unit (Atta Chakki & Masala Udyog)",
        "name_hi": "आटा चक्की एवं मसाला पिसाई उद्योग",
        "name_mr": "आटा चक्की आणि मसाला गिरणी उद्योग",
        "sector": "Agro-Processing & Village Services",
        "description": "Multi-grain flour milling, pulse de-husking (Dal mill), chili, turmeric and coriander pulverizing service and packaged spice blend manufacturing for village and township households.",
        "min_investment": 150000.0,
        "typical_investment": 260000.0,
        "max_investment": 650000.0,
        "typical_own_contribution_pct": 10.0,
        "equipment_needed": ["Commercial Atta Chakki (Emery Stone / SS Pulverizer)", "Micro Masala Pulverizer", "Cleaning Sieve / Destoner", "Pouch Heat Sealer", "Platform Weighing Scale"],
        "working_capital_months": 2,
        "typical_revenue_monthly": 38000.0,
        "typical_expenses_monthly": 18000.0,
        "profit_margin_range": "42% - 55%",
        "break_even_months": 6,
        "key_risks": [
            "Local competition from existing flour mills",
            "High commercial electricity tariff and voltage fluctuations",
            "Equipment wear & tear on pulverizer blades/stones"
        ],
        "mitigation_strategies": [
            "Offer value-added multi-grain flour mixes (Ragi, Jowar, Bajra, Soya) and branded village spices",
            "Apply for subsidized rural agricultural/MSME power tariff",
            "Routine preventive maintenance schedule"
        ],
        "required_documents": ["AADHAAR", "PAN", "ELECTRICITY_COMMERCIAL_SANCTION", "GRAM_PANCHAYAT_SHOP_NOC", "UDYAM_MSME"],
        "default_assumptions": {
            "parameters": [
                {
                    "parameter": "daily_flour_milling_kg",
                    "label": "Daily Flour Milling Volume",
                    "value": 150,
                    "unit": "kg / day",
                    "minimum": 60,
                    "maximum": 400,
                    "source": "Rural Micro-Enterprise Survey",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "milling_charge_per_kg",
                    "label": "Milling Service Charge",
                    "value": 6.5,
                    "unit": "₹ / kg",
                    "minimum": 4.5,
                    "maximum": 9.0,
                    "source": "Local Village Market Rates",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "spice_grinding_kg_daily",
                    "label": "Daily Spice Grinding Volume",
                    "value": 25,
                    "unit": "kg / day",
                    "minimum": 10,
                    "maximum": 80,
                    "source": "Local Market Benchmark",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "spice_grinding_charge_per_kg",
                    "label": "Spice Grinding Service Charge",
                    "value": 35.0,
                    "unit": "₹ / kg",
                    "minimum": 25.0,
                    "maximum": 50.0,
                    "source": "Local Village Tariff Benchmark",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "monthly_electricity_cost",
                    "label": "Monthly Electricity Expense",
                    "value": 5500.0,
                    "unit": "₹ / month",
                    "minimum": 2500.0,
                    "maximum": 12000.0,
                    "source": "State Electricity Board MSME Tariff",
                    "last_updated": "2026-08-01"
                }
            ]
        }
    },
    {
        "business_id": "BIZ_RURAL_KIRANA_CSC",
        "code": "RURAL_KIRANA_CSC",
        "name": "Smart Village Kirana & Digital CSC Kiosk",
        "name_hi": "स्मार्ट ग्रामीण किराना एवं डिजिटल सीएससी केंद्र",
        "name_mr": "स्मार्ट ग्रामीण किराणा व डिजिटल महा-ई-सेवा केंद्र",
        "sector": "Retail & Rural Citizen Services",
        "description": "Combined general grocery store, daily essentials retail, and Common Service Centre (CSC) offering banking BC services, AEPS cash withdrawal, government scheme applications, bill payments, and passport/PAN services.",
        "min_investment": 100000.0,
        "typical_investment": 180000.0,
        "max_investment": 400000.0,
        "typical_own_contribution_pct": 10.0,
        "equipment_needed": ["Laptop & Biometric Scanner (Morpho/Mantra)", "All-in-One Printer & Scanner", "Shop Racks & Display Shelves", "Deep Freezer / Refrigerator", "Micro-ATM Device"],
        "working_capital_months": 1,
        "typical_revenue_monthly": 34000.0,
        "typical_expenses_monthly": 14000.0,
        "profit_margin_range": "20% - 30%",
        "break_even_months": 5,
        "key_risks": [
            "Inventory expiration / non-moving items",
            "Slow broadband / mobile internet outages",
            "Credit (Udhaar) default by village customers"
        ],
        "mitigation_strategies": [
            "Fast-moving SKU focus with weekly replenishment from distributor",
            "Dual SIM 4G router with backup ISP",
            "Strict digital UPI payment policy (Paytm/PhonePe Soundbox) with minimum credit"
        ],
        "required_documents": ["AADHAAR", "PAN", "SHOP_ACT_OR_GRAM_PANCHAYAT_LICENSE", "IIBF_BC_CERTIFICATE_OR_CSC_ID", "POLICE_VERIFICATION"],
        "default_assumptions": {
            "parameters": [
                {
                    "parameter": "daily_kirana_sales",
                    "label": "Daily Grocery Sales",
                    "value": 3500,
                    "unit": "₹ / day",
                    "minimum": 1500,
                    "maximum": 9000,
                    "source": "Rural Retail Field Study",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "grocery_gross_margin_pct",
                    "label": "Average Grocery Profit Margin",
                    "value": 15.0,
                    "unit": "% of sales",
                    "minimum": 10.0,
                    "maximum": 22.0,
                    "source": "FMCG Distributor Standard Margins",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "daily_csc_transactions",
                    "label": "Daily Digital CSC / AEPS Transactions",
                    "value": 25,
                    "unit": "transactions / day",
                    "minimum": 10,
                    "maximum": 70,
                    "source": "CSC e-Governance Benchmark",
                    "last_updated": "2026-08-01"
                },
                {
                    "parameter": "commission_per_csc_txn",
                    "label": "Average Net Commission per Transaction",
                    "value": 22.0,
                    "unit": "₹ / transaction",
                    "minimum": 10.0,
                    "maximum": 45.0,
                    "source": "NPCI / BC Commission Tariff",
                    "last_updated": "2026-08-01"
                }
            ]
        }
    }
]
